INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('1', 'USER', '2018-02-12', '10.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('2', 'USER', '2018-02-22', '17.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('3', 'USER', '2018-02-13', '17.50', 'Dinner', 'dinner');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('4', 'USER', '2018-05-05', '17.50', 'Lanch', 'lanch');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('5', 'USER', '2018-01-06', '17.50', 'Lanch', 'lanch');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('6', 'USER', '2018-07-12', '17.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('7', 'USER', '2018-12-12', '17.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('9', 'USER', '2018-12-12', '17.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('10', 'USER', '2018-12-12', '17.50', 'Lanch', 'lanch');


INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('11', 'USER', '2019-02-12', '10.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('12', 'USER', '2019-02-12', '10.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('13', 'USER', '2019-02-12', '10.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('14', 'ANOTHER_USER', '2019-02-12', '10.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('15', 'ANOTHER_USER', '2019-02-12', '10.50', 'Super Market', 'super-market');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('16', 'ANOTHER_USER', '2019-02-12', '10.50', 'Super Market', 'super-market');

INSERT INTO BUDGET_EXPENSE_ATTACHMENTS(BUDGET_EXPENSE_ID, ATTACHMENT_NAME) VALUES ('13', 'attachment1.pdf');
INSERT INTO BUDGET_EXPENSE_ATTACHMENTS(BUDGET_EXPENSE_ID, ATTACHMENT_NAME) VALUES ('13', 'attachment2.pdf');
INSERT INTO BUDGET_EXPENSE_ATTACHMENTS(BUDGET_EXPENSE_ID, ATTACHMENT_NAME) VALUES ('13', 'attachment3.pdf');
