TRUNCATE TABLE BUDGET_EXPENSE

INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('1', 'USER', '2018-02-12', '10.50', 'NOTE', 'TAG');
INSERT INTO BUDGET_EXPENSE(ID, USER_NAME, DATE, AMOUNT, NOTE, TAG) VALUES ('2', 'USER', '2018-02-12', '17.50', 'NOTE', 'TAG');