version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: mvn clean install
      - run: docker login -u $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run: mvn docker:build docker:push