INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('1', 'USER', '2018-02-12', '10.50', 'Super Market');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('2', 'USER', '2018-02-22', '17.50', 'Super Market');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('3', 'USER', '2018-02-13', '17.50', 'Dinner');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('4', 'USER_1', '2018-05-05', '17.50', 'Lanch');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('5', 'USER', '2018-01-06', '17.50', 'Lanch');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('6', 'USER', '2018-07-12', '17.50', 'Super Market');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('7', 'USER', '2018-12-12', '17.50', 'Super Market');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('9', 'USER', '2018-12-12', '17.50', 'Super Market');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('10', 'USER', '2018-12-12', '17.50', 'Lanch');


INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('11', 'USER', '2019-02-12', '10.50', 'Super Market');
INSERT INTO BUDGET_REVENUE(ID, USER_NAME, REGISTRATION_DATE, AMOUNT, NOTE) VALUES ('12', 'USER', '2019-02-12', '10.50', 'Super Market');