INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('parcking', 'Parcheggio');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('autobus-ticket', 'Autobus');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('chancellery', 'Cancelleria');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('loan', 'Rata Prestito');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('train-ticket', 'Treno');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('bar', 'Bar');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('dinner', 'Cena');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('rent', 'Rata Affitto');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('super-market', 'Spesa');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('travel', 'Viaggio');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('ironmongery', 'Ferramenta');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('souvenir', 'Souvenir');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('coffie-bar', 'Caffetteria');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('parking', 'Parcheggio');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('present', 'Regalo');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('amazon', 'Amazon');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('fuel', 'Carburante');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('lunch', 'Pranzo');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('unknown', 'Sconosciuto');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('domestic-appliances', 'Elettrodomestici');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('telephone-top-up', 'Ricarica Telefonica');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('bill', 'Bolletta');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('pharmacy', 'Farmacia');
INSERT INTO SEARCH_TAG(KEY, VALUE) VALUES ('hair-styling', 'Barbiere/Parrucchiere');